//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cactus.Core.UI.UserControls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class General_Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General_Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cactus.Core.UI.UserControls.General_Res", typeof(General_Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا اطمینان داریدازحذف کاربر  ؟.
        /// </summary>
        internal static string AreYouDeleteUser {
            get {
                return ResourceManager.GetString("AreYouDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Cactus_icon {
            get {
                object obj = ResourceManager.GetObject("Cactus_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجازه تغییر نام کاربری را ندارید .
        /// </summary>
        internal static string ChangeUserName {
            get {
                return ResourceManager.GetString("ChangeUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتباط برقرار می باشد.
        /// </summary>
        internal static string Communication {
            get {
                return ResourceManager.GetString("Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان وارد شده  در سیستم وجود دارد .
        /// </summary>
        internal static string DuplicateRoleTitle {
            get {
                return ResourceManager.GetString("DuplicateRoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری قبلا در سیستم ثبت شده است .
        /// </summary>
        internal static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابتدا اطلاعات سرور را وارد کنید.
        /// </summary>
        internal static string EnterServerInformation {
            get {
                return ResourceManager.GetString("EnterServerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه اصلی.
        /// </summary>
        internal static string FT_Start {
            get {
                return ResourceManager.GetString("FT_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ وارد شده صیح نمی باشد  .
        /// </summary>
        internal static string ISIncorrectDate {
            get {
                return ResourceManager.GetString("ISIncorrectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول کد وارد صحیح نمی باشد .
        /// </summary>
        internal static string LengthCode {
            get {
                return ResourceManager.GetString("LengthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما به این بخش دسترسی ندارید .
        /// </summary>
        internal static string NOAccess {
            get {
                return ResourceManager.GetString("NOAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتباط  برقرار نیست .
        /// </summary>
        internal static string NoCommunication {
            get {
                return ResourceManager.GetString("NoCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هرکاربر برای حداقل یک نقش در سیستم داشته باشد .
        /// </summary>
        internal static string NoRole {
            get {
                return ResourceManager.GetString("NoRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات را به درستی وارد کنید .
        /// </summary>
        internal static string NothingEnterInformation {
            get {
                return ResourceManager.GetString("NothingEnterInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار رمز تطابق ندارد.
        /// </summary>
        internal static string NoValidConfirmPass {
            get {
                return ResourceManager.GetString("NoValidConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز وارد با رمز قبلی تطابق ندارد.
        /// </summary>
        internal static string NoValidPreviousPass {
            get {
                return ResourceManager.GetString("NoValidPreviousPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  اصلاعات واردشده معتبر نمی باشد .
        /// </summary>
        internal static string NoValidUser {
            get {
                return ResourceManager.GetString("NoValidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ای وای 
        ///عملیات شکست خورد لطفا مجدد تلاش کنید.
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد .
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
