//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cactus.Inventory.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Form_Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form_Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cactus.Inventory.UI.Resources.Form_Res", typeof(Form_Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالا جدید.
        /// </summary>
        internal static string FT_AddGoods {
            get {
                return ResourceManager.GetString("FT_AddGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انبار جدید.
        /// </summary>
        internal static string FT_AddInventory {
            get {
                return ResourceManager.GetString("FT_AddInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند جدید.
        /// </summary>
        internal static string FT_AddTransaction {
            get {
                return ResourceManager.GetString("FT_AddTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی .
        /// </summary>
        internal static string FT_Category {
            get {
                return ResourceManager.GetString("FT_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش کالا.
        /// </summary>
        internal static string FT_EditGoods {
            get {
                return ResourceManager.GetString("FT_EditGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش انبار.
        /// </summary>
        internal static string FT_EditInventory {
            get {
                return ResourceManager.GetString("FT_EditInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش سند.
        /// </summary>
        internal static string FT_EditTransaction {
            get {
                return ResourceManager.GetString("FT_EditTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالا.
        /// </summary>
        internal static string FT_Goods {
            get {
                return ResourceManager.GetString("FT_Goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انبار.
        /// </summary>
        internal static string FT_Inventory {
            get {
                return ResourceManager.GetString("FT_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش.
        /// </summary>
        internal static string FT_Report {
            get {
                return ResourceManager.GetString("FT_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی انبار.
        /// </summary>
        internal static string FT_Storyinventory {
            get {
                return ResourceManager.GetString("FT_Storyinventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند.
        /// </summary>
        internal static string FT_Transactio {
            get {
                return ResourceManager.GetString("FT_Transactio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconCustomer {
            get {
                object obj = ResourceManager.GetObject("IconCustomer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconEditCustomer {
            get {
                object obj = ResourceManager.GetObject("IconEditCustomer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconEditGoods {
            get {
                object obj = ResourceManager.GetObject("IconEditGoods", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconEditInventory {
            get {
                object obj = ResourceManager.GetObject("IconEditInventory", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconEditTransaction {
            get {
                object obj = ResourceManager.GetObject("IconEditTransaction", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconGoods {
            get {
                object obj = ResourceManager.GetObject("IconGoods", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconInventory {
            get {
                object obj = ResourceManager.GetObject("IconInventory", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconNewCustomer {
            get {
                object obj = ResourceManager.GetObject("IconNewCustomer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconNewGoods {
            get {
                object obj = ResourceManager.GetObject("IconNewGoods", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconNewInventory {
            get {
                object obj = ResourceManager.GetObject("IconNewInventory", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconNewTransaction {
            get {
                object obj = ResourceManager.GetObject("IconNewTransaction", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconReport {
            get {
                object obj = ResourceManager.GetObject("IconReport", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconTag {
            get {
                object obj = ResourceManager.GetObject("IconTag", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconTranaction {
            get {
                object obj = ResourceManager.GetObject("IconTranaction", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pin {
            get {
                object obj = ResourceManager.GetObject("Pin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
