//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cactus.Inventory.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Goods_Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Goods_Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cactus.Inventory.UI.Resources.Goods_Res", typeof(Goods_Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا اطمینان دارید از حذف دسته بندی ؟.
        /// </summary>
        internal static string AreYouDeleteCategory {
            get {
                return ResourceManager.GetString("AreYouDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا اطمینان دارید از حذف کالا؟.
        /// </summary>
        internal static string AreYouDeleteGoods {
            get {
                return ResourceManager.GetString("AreYouDeleteGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خالی بودن مقادیر  .
        /// </summary>
        internal static string CaptionEmptyFields {
            get {
                return ResourceManager.GetString("CaptionEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد کالا نباید تغییر کند  .
        /// </summary>
        internal static string ConversionGoodsCode {
            get {
                return ResourceManager.GetString("ConversionGoodsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف نا موفق است 
        ///مجدد تلاش کنید .
        /// </summary>
        internal static string DeleteCategoryNotSuccessful {
            get {
                return ResourceManager.GetString("DeleteCategoryNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف با موفقیت انجام شد  .
        /// </summary>
        internal static string DeleteCategorySuccessful {
            get {
                return ResourceManager.GetString("DeleteCategorySuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالای مورد نظر با موفقیت حذف شد .
        /// </summary>
        internal static string DeleteGoods {
            get {
                return ResourceManager.GetString("DeleteGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شد تکراری می باشد .
        /// </summary>
        internal static string DuplicateGoodsCode {
            get {
                return ResourceManager.GetString("DuplicateGoodsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالا.
        /// </summary>
        internal static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالا با موفقیت حذف شد .
        /// </summary>
        internal static string MTDeleted {
            get {
                return ResourceManager.GetString("MTDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به دلیل  وجود معامله برای این  کالا شما اجازه حذف آن را ندارید.
        /// </summary>
        internal static string NoDelete {
            get {
                return ResourceManager.GetString("NoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالا باید حداقل در یک دسته بندی قرار گیرد.
        /// </summary>
        internal static string NoEnterCatgory {
            get {
                return ResourceManager.GetString("NoEnterCatgory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات را به درستی وارد کنید .
        /// </summary>
        internal static string NothingEnterInformation {
            get {
                return ResourceManager.GetString("NothingEnterInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با موفقیت ثبت شد   .
        /// </summary>
        internal static string SuccessInsert {
            get {
                return ResourceManager.GetString("SuccessInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف دسته بندی به دلیل وجودکالا در این دسته بندی,وجودندارد .
        /// </summary>
        internal static string ThisisCategoryInGoods {
            get {
                return ResourceManager.GetString("ThisisCategoryInGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد خالی .
        /// </summary>
        internal static string TitileMessageBoxNullControls {
            get {
                return ResourceManager.GetString("TitileMessageBoxNullControls", resourceCulture);
            }
        }
    }
}
