//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cactus.Inventory.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Inventory_Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Inventory_Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cactus.Inventory.UI.Resources.Inventory_Res", typeof(Inventory_Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا اطمینان دارید از حذف انبار؟.
        /// </summary>
        internal static string AreYouDelelteInventory {
            get {
                return ResourceManager.GetString("AreYouDelelteInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خالی بودن مقادیر  .
        /// </summary>
        internal static string CaptionEmptyFields {
            get {
                return ResourceManager.GetString("CaptionEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجازه تغییر کد انبار وجود ندارد .
        /// </summary>
        internal static string ConversionCode {
            get {
                return ResourceManager.GetString("ConversionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                                                 :هشدار  
        ///
        /// با حذف کالا تمامی حواله و رسید صادر شده این انبار 
        ///                                                                  حذف خواهد شد.
        /// </summary>
        internal static string DeletAlert {
            get {
                return ResourceManager.GetString("DeletAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انبار مورد نظر با موفقیت حذف شد .
        /// </summary>
        internal static string DeleteInventory {
            get {
                return ResourceManager.GetString("DeleteInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شد تکراری می باشد .
        /// </summary>
        internal static string DuplicateInventoryCode {
            get {
                return ResourceManager.GetString("DuplicateInventoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انبار.
        /// </summary>
        internal static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انبار با موفقیت حذف شد .
        /// </summary>
        internal static string MTDeleted {
            get {
                return ResourceManager.GetString("MTDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  به دلیل  وجود کالا و معامله برای انبار انتخاب شده امکان  حذف  آن وجود ندارد .
        /// </summary>
        internal static string NoDelete {
            get {
                return ResourceManager.GetString("NoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات را به درستی وارد کنید .
        /// </summary>
        internal static string NothingEnterInformation {
            get {
                return ResourceManager.GetString("NothingEnterInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابتدا انبار را مشخص کنید.
        /// </summary>
        internal static string SelectionInventory {
            get {
                return ResourceManager.GetString("SelectionInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انبار با موفقیت  ثبت شد.
        /// </summary>
        internal static string SuccessInsertInventory {
            get {
                return ResourceManager.GetString("SuccessInsertInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد خالی .
        /// </summary>
        internal static string TitileMessageBoxNullControls {
            get {
                return ResourceManager.GetString("TitileMessageBoxNullControls", resourceCulture);
            }
        }
    }
}
