//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cactus.Inventory.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Transaction_Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Transaction_Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cactus.Inventory.UI.Resources.Transaction_Res", typeof(Transaction_Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایا اطمینان دارید برای حذف ؟
        ///هشدار: با حذف سند موجودی انبار تغییر خواهد کرد.
        /// </summary>
        internal static string AreYouSureDelete {
            get {
                return ResourceManager.GetString("AreYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خالی بودن مقادیر  .
        /// </summary>
        internal static string CaptionEmptyFields {
            get {
                return ResourceManager.GetString("CaptionEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد سفارش نباید تغییر کند.
        /// </summary>
        internal static string ConversionCode {
            get {
                return ResourceManager.GetString("ConversionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابتدا باید مشخصات مربوط به فاکتور را وارد کنید.
        /// </summary>
        internal static string EnterTransactionFields {
            get {
                return ResourceManager.GetString("EnterTransactionFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  بازه زمانی وارده صحیح نمی باشد .
        /// </summary>
        internal static string ErrorTime {
            get {
                return ResourceManager.GetString("ErrorTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  برای انتخاب  کافیست از فهرست  دوبار بر روی فیلد مورد نظر کلیک کنید.
        /// </summary>
        internal static string guideSelected {
            get {
                return ResourceManager.GetString("guideSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Hopstarter_Book_Address_Book_Mac__1_ {
            get {
                object obj = ResourceManager.GetObject("Hopstarter_Book_Address_Book_Mac__1_", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالا  در حال ثبت بیش از موجود انبار می باشد  .
        /// </summary>
        internal static string InsertMoreStock {
            get {
                return ResourceManager.GetString("InsertMoreStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد سفارش قبلا ثبت شده .
        /// </summary>
        internal static string MessageDuplicateCode {
            get {
                return ResourceManager.GetString("MessageDuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardex.mrt.
        /// </summary>
        internal static string PrintCardexFileName {
            get {
                return ResourceManager.GetString("PrintCardexFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockInventoryReport.mrt.
        /// </summary>
        internal static string PrintStockInventoryFileName {
            get {
                return ResourceManager.GetString("PrintStockInventoryFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintTransaction.mrt.
        /// </summary>
        internal static string PrintTransactionFileName {
            get {
                return ResourceManager.GetString("PrintTransactionFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با موفقیت  حذف شد .
        /// </summary>
        internal static string SuccessDelete {
            get {
                return ResourceManager.GetString("SuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موفقیت  ثبت شد.
        /// </summary>
        internal static string SuccessInsert {
            get {
                return ResourceManager.GetString("SuccessInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        internal static string TitileError {
            get {
                return ResourceManager.GetString("TitileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد خالی .
        /// </summary>
        internal static string TitileMessageBoxNullControls {
            get {
                return ResourceManager.GetString("TitileMessageBoxNullControls", resourceCulture);
            }
        }
    }
}
