//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cactus.Contact.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Contact_Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Contact_Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cactus.Contact.UI.Resources.Contact_Res", typeof(Contact_Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشدار: با حذف مشتری تمامی حواله و رسید صادره حذف خواهد شد .
        /// </summary>
        internal static string AlertDeleteContact {
            get {
                return ResourceManager.GetString("AlertDeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا اطمینان دارید از حذف مشتری؟.
        /// </summary>
        internal static string AreYouDeleteContact {
            get {
                return ResourceManager.GetString("AreYouDeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف مشتری.
        /// </summary>
        internal static string CaptionDeleteContact {
            get {
                return ResourceManager.GetString("CaptionDeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خالی بودن مقادیر  .
        /// </summary>
        internal static string CaptionEmptyFields {
            get {
                return ResourceManager.GetString("CaptionEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --انتخاب کنید--.
        /// </summary>
        internal static string ComboboxDefaultValue {
            get {
                return ResourceManager.GetString("ComboboxDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد شخص  نباید تغییر کند .
        /// </summary>
        internal static string ConversionContactCode {
            get {
                return ResourceManager.GetString("ConversionContactCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری با موفقیت حذف گردید .
        /// </summary>
        internal static string DeletedContact {
            get {
                return ResourceManager.GetString("DeletedContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شد تکراری می باشد .
        /// </summary>
        internal static string DuplicateContactCode {
            get {
                return ResourceManager.GetString("DuplicateContactCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدول اماده ویرایش هست .
        /// </summary>
        internal static string EditGrid {
            get {
                return ResourceManager.GetString("EditGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک کد شخص وارد کنید.
        /// </summary>
        internal static string EnterContactCode {
            get {
                return ResourceManager.GetString("EnterContactCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک نام پدر وارد کنید .
        /// </summary>
        internal static string EnterFatherName {
            get {
                return ResourceManager.GetString("EnterFatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک نام  وارد کنید.
        /// </summary>
        internal static string EnterFristName {
            get {
                return ResourceManager.GetString("EnterFristName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک نام خانوادگی وارد کنید .
        /// </summary>
        internal static string EnterLastName {
            get {
                return ResourceManager.GetString("EnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک کد ملی وارد کنید .
        /// </summary>
        internal static string EnterNationalCode {
            get {
                return ResourceManager.GetString("EnterNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری.
        /// </summary>
        internal static string FormContactListTitle {
            get {
                return ResourceManager.GetString("FormContactListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این فرم فقط برای نمایش  اطلاعات می باشد.
        /// </summary>
        internal static string FormInsertUpdateTitleInModeReview {
            get {
                return ResourceManager.GetString("FormInsertUpdateTitleInModeReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ثبت مشتری جدید.
        /// </summary>
        internal static string FormInsertUpdateTitleModeNew {
            get {
                return ResourceManager.GetString("FormInsertUpdateTitleModeNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ویرایش مشتری .
        /// </summary>
        internal static string FormInsertUpdateTitleModeUpdate {
            get {
                return ResourceManager.GetString("FormInsertUpdateTitleModeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم چاپ.
        /// </summary>
        internal static string FormPrintContactTitle {
            get {
                return ResourceManager.GetString("FormPrintContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن آدرس .
        /// </summary>
        internal static string FormTitleSetAddress {
            get {
                return ResourceManager.GetString("FormTitleSetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن شماره تلفن .
        /// </summary>
        internal static string FormTitleSetPhone {
            get {
                return ResourceManager.GetString("FormTitleSetPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات فرد با موفقیت ثبت گردید..
        /// </summary>
        internal static string InsertedContact {
            get {
                return ResourceManager.GetString("InsertedContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما  به دلیل  وجود معامله برای این مشتری در سیستم اجازه حذف آن را ندارید .
        /// </summary>
        internal static string NoDeleteContact {
            get {
                return ResourceManager.GetString("NoDeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای چاپ یک کد مخاطب وارد کنید
        /// در غیر این صورت ابتدا از جدول در فرم قبل یک مخاطب را انتخاب کرده
        /// سپس دکمه چاپ را فشار دهید  کنید .
        /// </summary>
        internal static string NoEnterContactCodeToPrint {
            get {
                return ResourceManager.GetString("NoEnterContactCodeToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخاطب وجود ندارد.
        /// </summary>
        internal static string notExistContact {
            get {
                return ResourceManager.GetString("notExistContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات را به درستی وارد کنید .
        /// </summary>
        internal static string NothingEnterInformation {
            get {
                return ResourceManager.GetString("NothingEnterInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن وارد شد صحیح نمی باشد  .
        /// </summary>
        internal static string PhonePatternIncorrect {
            get {
                return ResourceManager.GetString("PhonePatternIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای جستجو حداقل یکی از مواد مشخص شده را وارد کنید.
        /// </summary>
        internal static string SearchContact {
            get {
                return ResourceManager.GetString("SearchContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی وارد شده صیح نمی باشد .
        /// </summary>
        internal static string TheNationalCodeIsInCorrect {
            get {
                return ResourceManager.GetString("TheNationalCodeIsInCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد خالی .
        /// </summary>
        internal static string TitileMessageBoxNullControls {
            get {
                return ResourceManager.GetString("TitileMessageBoxNullControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات مشتری با موفقیت بروز رسانی شد .
        /// </summary>
        internal static string UpdatedContact {
            get {
                return ResourceManager.GetString("UpdatedContact", resourceCulture);
            }
        }
    }
}
